variables:
  BuildConfiguration: 'Release'

trigger:
- none

pool:
  vmImage: 'macOS-10.13'

steps:
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install an Apple provisioning profile'
  inputs:
    provProfileSecureFile: 'VS_WildCard_Development.mobileprovision'

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple Development Certificate Aram Maliachi'
  inputs:
    certSecureFile: 'Aram Maliachi.p12'
    certPwd: Madeleine1789
    signingIdentity: 'Developer: Aram Maliachi (M45XFJ5VN8)'

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple Development Certificate Wipro Macbook'
  inputs:
    certSecureFile: 'Certificate-wipro.p12'
    certPwd: Madeleine1789

- task: InstallAppleCertificate@2
  displayName: 'Install an Apple Development Certificate M45XFJ5VN8'
  inputs:
    certSecureFile: 'Certificates-M45XFJ5VN8.p12'
    certPwd: Madeleine1789

- bash: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0'
  displayName: 'Select Xamarin SDK version'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.3.0'
  inputs:
    versionSpec: 4.3.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS solution xamarinforms/xamarinforms.iOS/xamarinforms.iOS.csproj'
  inputs:
    solutionFile: xamarinforms/xamarinforms.iOS/xamarinforms.iOS.csproj
    configuration: '$(BuildConfiguration)'
    packageApp: true

- bash: |
   cd $(Build.Repository.LocalPath)
   cd xamarinforms
   cd xamarinforms.iOS
   cd bin
   cd iPhone
   cd Release
   pwd
   ls
  displayName: 'Find the .dSYM'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/xamarinforms/xamarinforms.iOS/bin/iPhone/Release'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'